//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorXflow.Data
{
    using System;
    
    public enum Type : int
    {
        Direct = 0,
        Broadcast = 1,
        Error = 2,
        Connect = 3,
        Disconnect = 4
    }
}
