//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorXflow.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WebMessage
    {
        public int Id { get; set; }
        public string Text { get; set; }
        public Type Type { get; set; }
        public string User { get; set; }
    }
}
